apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydotnetapp   # 👈 CHANGE: match pipeline
  labels:
    app: mydotnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydotnetapp
  template:
    metadata:
      labels:
        app: mydotnetapp
    spec:
      containers:
      - name: mydotnetapp
        image: myacr123456r.azurecr.io/mydotnetapp:latest
        ports:
        - containerPort: 80
